#!/bin/sh -eux

ub_install

mkdir -p "$UB_INSTALLDIR"/usr/lib/pkgconfig
mv "$UB_INSTALLDIR"/usr/share/pkgconfig/mdds.pc "$UB_INSTALLDIR"/usr/lib/pkgconfig/
rm -Rf "$UB_INSTALLDIR"/usr/share/pkgconfig
