#!/bin/sh -eux

autoreconf -vif
ub_configure \
	--enable-gradients \
	--enable-shape \
	--enable-shaped-decorations \
	--enable-fribidi \
	--enable-i18n \
	--without-esd-config
sed -i "s:/icewm-\$(VERSION)::" src/Makefile || die "patch failed"
sed -i "s:ungif:gif:" src/Makefile || die "libungif fix failed"
#sed -i '/^CORE_LIBS/aCORE_LIBS += -lfontconfig' src/Makefile

ub_make
