#!/bin/sh -eux

ub_install 
sed s@#" "IconPath.*@IconPath=/usr/share/pixmaps:/usr/share/icons/hicolor/48x48/apps:/usr/share/icons/gnome/48x48/apps:/usr/share/icons/gnome/48x48/actions:/usr/share/icons/gnome/48x48/devices:/usr/share/icons/default.kde4/48x48/apps@ -i \
	src/preferences
cp src/preferences ${UB_INSTALLDIR}/usr/share/icewm/
cp src/genpref ${UB_INSTALLDIR}/usr/bin/
