#!/bin/sh -eux

if [ ! -f version ]; then
	echo "echo $UB_VERSION" > version
fi

autoreconf -vif

# GData: libgdata 0.17.1, inkább 0.17.2
# Geolocation: régi libchamplain (0.8) kell

ub_compile \
    --enable-crash-dialog \
    --disable-gtk3 \
    --disable-ldap \
    --disable-jpilot \
    --disable-bsfilter-plugin \
	--disable-gdata-plugin
