#!/bin/sh -eux

# export CFLAGS='-D_FILE_OFFSET_BITS=64'
# sed -i -e 's/indicate-0.5/indicate-0.6/g' configure.ac

autoreconf -vif

ub_compile \
    --enable-crash-dialog \
    --disable-gtk3 \
    --disable-ldap \
    --disable-jpilot \
    --disable-bsfilter-plugin

