#!/bin/sh -eux

ub_install
mkdir -p ${UB_INSTALLDIR}/etc/xdg
cp -r ${UB_INSTALLDIR}/usr/lib/qt5/etc/xdg/* ${UB_INSTALLDIR}/etc/xdg/
#cp menu/lxqt-applications.menu ${UB_INSTALLDIR}/etc/xdg/menus/
#ln -s /usr/lib/qt5/etc/xdg/pcmanfm-qt ${UB_INSTALLDIR}/etc/xdg/pcmanfm-qt

