#!/bin/sh -eux

export WX_CONFIG=/usr/bin/wx-config2

cd build/workspaces
./update-workspaces.sh \
      --with-system-miniupnpc \
      --bindir=/usr/bin \
      --libdir=/usr/lib/0ad \
      --datadir=/usr/share/0ad/data \
      --with-system-mozjs24 \
      --sdl2
cd gcc
ub_make
