#!/bin/sh -eux

make -C buildCli DESTDIR=${UB_INSTALLDIR} install
make -C buildCore DESTDIR=${UB_INSTALLDIR} install
make -C buildPluginsCLI DESTDIR=${UB_INSTALLDIR} install
make -C buildPluginsCommon DESTDIR=${UB_INSTALLDIR} install
make -C buildQt5 DESTDIR=${UB_INSTALLDIR} install
make -C buildPluginsQt5 DESTDIR=${UB_INSTALLDIR} install
mkdir -p "${UB_INSTALLDIR}"/usr/share/{avidemux6,pixmaps,applications}
cp avidemux_icon.png ${UB_INSTALLDIR}/usr/share/pixmaps/avidemux.png
cp avidemux2.desktop "${UB_INSTALLDIR}"/usr/share/applications/avidemux3.desktop
cp man/avidemux.1 ${UB_INSTALLDIR}/usr/share/man/man1/
ln -s avidemux3_qt5 "${UB_INSTALLDIR}"/usr/bin/avidemux
rm -rf ${UB_INSTALLDIR}/usr/share/ADM6_addons
